name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
    - name: Build
      run: ./scripts/nix-cargo build --verbose
    - name: Run tests
      run: ./scripts/nix-cargo build --verbose test --verbose
